UPDATE prospect_searches SET country = CASE city
  WHEN 'Madrid' THEN 'España'
  WHEN 'Barcelona' THEN 'España'
  WHEN 'Valencia' THEN 'España'
  WHEN 'Sevilla' THEN 'España'
  WHEN 'Bilbao' THEN 'España'
  WHEN 'Bogotá' THEN 'Colombia'
  WHEN 'Medellín' THEN 'Colombia'
  WHEN 'Cali' THEN 'Colombia'
  WHEN 'Buenos Aires' THEN 'Argentina'
  WHEN 'Santiago de Chile' THEN 'Chile'
  WHEN 'Lima' THEN 'Perú'
  WHEN 'Miami' THEN 'Estados Unidos'
  WHEN 'Houston' THEN 'Estados Unidos'
  WHEN 'Los Ángeles' THEN 'Estados Unidos'
  WHEN 'Chicago' THEN 'Estados Unidos'
  WHEN 'Nueva York' THEN 'Estados Unidos'
  WHEN 'Ciudad de Panamá' THEN 'Panamá'
  WHEN 'Caracas' THEN 'Venezuela'
  WHEN 'Quito' THEN 'Ecuador'
  WHEN 'Montevideo' THEN 'Uruguay'
  ELSE 'México'
END;
