-- Create table
CREATE TABLE IF NOT EXISTS prospect_searches (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  query text NOT NULL,
  city text NOT NULL,
  country text DEFAULT 'México',
  active boolean DEFAULT true,
  last_run timestamptz,
  created_at timestamptz DEFAULT now()
);

-- Seed 500+ searches
INSERT INTO prospect_searches (query, city, active) VALUES
('talleres mecánicos', 'Monterrey', true),
('psicólogos', 'Montevideo', true),
('lavanderías', 'Montevideo', true),
('ópticas', 'Tijuana', true),
('gimnasios', 'Bilbao', true),
('joyerías', 'Puebla', true),
('despachos de arquitectura', 'Miami', true),
('despachos de arquitectura', 'Sevilla', true),
('farmacias', 'Medellín', true),
('ópticas', 'Monterrey', true),
('infoproductores', 'Caracas', true),
('nutriólogos', 'Medellín', true),
('agencias de marketing', 'Valencia', true),
('cafeterías', 'Barcelona', true),
('escuelas privadas', 'Lima', true),
('barberías', 'Chicago', true),
('joyerías', 'Chicago', true),
('nutriólogos', 'Bilbao', true),
('talleres mecánicos', 'Santiago de Chile', true),
('floristerías', 'Mérida', true),
('agencias de eventos', 'Querétaro', true),
('veterinarias', 'Ciudad de México', true),
('lavanderías', 'Madrid', true),
('floristerías', 'Lima', true),
('tiendas de ropa', 'Buenos Aires', true),
('infoproductores', 'Tijuana', true),
('lavanderías', 'Los Ángeles', true),
('psicólogos', 'Miami', true),
('despachos de arquitectura', 'Monterrey', true),
('despachos de arquitectura', 'Tijuana', true),
('academias de idiomas', 'Lima', true),
('empresas de logística', 'Bogotá', true),
('restaurantes', 'Montevideo', true),
('cafeterías', 'Puebla', true),
('psicólogos', 'Buenos Aires', true),
('academias de baile', 'Ciudad de México', true),
('clínicas dentales', 'Chicago', true),
('tiendas de ropa', 'Cali', true),
('fábricas', 'Buenos Aires', true),
('clínicas de estética', 'Caracas', true),
('agencias de eventos', 'Monterrey', true),
('imprentas', 'Buenos Aires', true),
('talleres mecánicos', 'Montevideo', true),
('academias de idiomas', 'Caracas', true),
('agencias de viajes', 'Madrid', true),
('escuelas privadas', 'Caracas', true),
('floristerías', 'Miami', true),
('veterinarias', 'Los Ángeles', true),
('joyerías', 'Houston', true),
('academias de baile', 'Barcelona', true),
('nutriólogos', 'Madrid', true),
('guarderías', 'Ciudad de Panamá', true),
('empresas de logística', 'Santiago de Chile', true),
('veterinarias', 'Tijuana', true),
('estudios de fotografía', 'Tijuana', true),
('estudios de tatuaje', 'Valencia', true),
('contadores', 'Buenos Aires', true),
('joyerías', 'Tijuana', true),
('fábricas', 'Miami', true),
('clínicas dentales', 'Valencia', true),
('restaurantes', 'Quito', true),
('floristerías', 'Nueva York', true),
('clínicas de estética', 'Montevideo', true),
('barberías', 'Bilbao', true),
('contadores', 'Valencia', true),
('escuelas privadas', 'León', true),
('inmobiliarias', 'Monterrey', true),
('imprentas', 'Puebla', true),
('inmobiliarias', 'Los Ángeles', true),
('talleres mecánicos', 'Buenos Aires', true),
('gimnasios', 'Bogotá', true),
('empresas de logística', 'Mérida', true),
('lavanderías', 'Buenos Aires', true),
('veterinarias', 'Montevideo', true),
('estudios de tatuaje', 'Buenos Aires', true),
('barberías', 'Los Ángeles', true),
('coaches de negocios', 'Los Ángeles', true),
('restaurantes', 'Tijuana', true),
('escuelas privadas', 'Miami', true),
('tiendas de ropa', 'León', true),
('nutriólogos', 'Puebla', true),
('distribuidoras', 'Chicago', true),
('academias de idiomas', 'Ciudad de Panamá', true),
('guarderías', 'Houston', true),
('academias de baile', 'Lima', true),
('fábricas', 'Querétaro', true),
('distribuidoras', 'Buenos Aires', true),
('academias de idiomas', 'Houston', true),
('cafeterías', 'Valencia', true),
('floristerías', 'Monterrey', true),
('gimnasios', 'Montevideo', true),
('agencias de viajes', 'León', true),
('inmobiliarias', 'Ciudad de Panamá', true),
('cafeterías', 'Quito', true),
('academias de idiomas', 'Valencia', true),
('floristerías', 'León', true),
('farmacias', 'Caracas', true),
('cafeterías', 'Bogotá', true),
('ópticas', 'Los Ángeles', true),
('fábricas', 'Ciudad de México', true),
('infoproductores', 'Medellín', true),
('hoteles', 'Nueva York', true),
('talleres mecánicos', 'Houston', true),
('hoteles', 'Mérida', true),
('estudios de tatuaje', 'Cali', true),
('farmacias', 'León', true),
('constructoras', 'Chicago', true),
('barberías', 'Medellín', true),
('infoproductores', 'Sevilla', true),
('barberías', 'Madrid', true),
('empresas de logística', 'Guadalajara', true),
('centros de coworking', 'Ciudad de México', true),
('agencias de viajes', 'Chicago', true),
('contadores', 'Quito', true),
('guarderías', 'Miami', true),
('tiendas de ropa', 'Caracas', true),
('fábricas', 'Tijuana', true),
('contadores', 'Montevideo', true),
('abogados', 'León', true),
('spas', 'Ciudad de México', true),
('estudios de fotografía', 'Chicago', true),
('academias de baile', 'León', true),
('centros de coworking', 'Quito', true),
('barberías', 'Tijuana', true),
('ópticas', 'Santiago de Chile', true),
('estudios de tatuaje', 'Monterrey', true),
('contadores', 'Lima', true),
('despachos de arquitectura', 'Chicago', true),
('coaches de negocios', 'Ciudad de México', true),
('restaurantes', 'Monterrey', true),
('empresas de logística', 'Tijuana', true),
('estudios de fotografía', 'Cali', true),
('clínicas dentales', 'Guadalajara', true),
('veterinarias', 'Santiago de Chile', true),
('estudios de fotografía', 'Madrid', true),
('escuelas privadas', 'Sevilla', true),
('spas', 'Los Ángeles', true),
('despachos de arquitectura', 'Barcelona', true),
('psicólogos', 'Guadalajara', true),
('empresas de logística', 'León', true),
('agencias de eventos', 'Mérida', true),
('centros de coworking', 'Lima', true),
('infoproductores', 'Los Ángeles', true),
('agencias de marketing', 'Ciudad de México', true),
('veterinarias', 'Sevilla', true),
('coaches de negocios', 'Puebla', true),
('gimnasios', 'Nueva York', true),
('contadores', 'Tijuana', true),
('guarderías', 'Lima', true),
('contadores', 'Ciudad de México', true),
('agencias de eventos', 'Valencia', true),
('centros de coworking', 'Sevilla', true),
('gimnasios', 'Miami', true),
('agencias de marketing', 'Caracas', true),
('abogados', 'Caracas', true),
('estudios de fotografía', 'Ciudad de Panamá', true),
('escuelas privadas', 'Guadalajara', true),
('ópticas', 'Miami', true),
('constructoras', 'Ciudad de Panamá', true),
('psicólogos', 'Santiago de Chile', true),
('lavanderías', 'Valencia', true),
('psicólogos', 'Cali', true),
('psicólogos', 'Ciudad de Panamá', true),
('inmobiliarias', 'Sevilla', true),
('contadores', 'Barcelona', true),
('joyerías', 'Guadalajara', true),
('hoteles', 'León', true),
('agencias de marketing', 'Madrid', true),
('consultorías empresariales', 'Quito', true),
('clínicas de estética', 'Mérida', true),
('gimnasios', 'Houston', true),
('farmacias', 'Ciudad de Panamá', true),
('clínicas de estética', 'Houston', true),
('lavanderías', 'Monterrey', true),
('ópticas', 'Ciudad de Panamá', true),
('abogados', 'Mérida', true),
('hoteles', 'Medellín', true),
('ópticas', 'Mérida', true),
('fábricas', 'León', true),
('farmacias', 'Montevideo', true),
('agencias de viajes', 'Tijuana', true),
('contadores', 'Los Ángeles', true),
('spas', 'Santiago de Chile', true),
('clínicas dentales', 'Tijuana', true),
('restaurantes', 'Chicago', true),
('centros de coworking', 'Buenos Aires', true),
('psicólogos', 'Puebla', true),
('guarderías', 'Ciudad de México', true),
('distribuidoras', 'Montevideo', true),
('spas', 'Montevideo', true),
('clínicas dentales', 'Bilbao', true),
('estudios de fotografía', 'Bogotá', true),
('inmobiliarias', 'Quito', true),
('consultorías empresariales', 'Barcelona', true),
('consultorías empresariales', 'Puebla', true),
('agencias de viajes', 'Medellín', true),
('distribuidoras', 'Tijuana', true),
('nutriólogos', 'Guadalajara', true),
('farmacias', 'Bogotá', true),
('academias de idiomas', 'Montevideo', true),
('veterinarias', 'Caracas', true),
('agencias de viajes', 'Guadalajara', true),
('hoteles', 'Houston', true),
('tiendas de ropa', 'Barcelona', true),
('coaches de negocios', 'Tijuana', true),
('academias de idiomas', 'Madrid', true),
('distribuidoras', 'Barcelona', true),
('agencias de marketing', 'Los Ángeles', true),
('floristerías', 'Buenos Aires', true),
('ópticas', 'Nueva York', true),
('imprentas', 'Querétaro', true),
('hoteles', 'Ciudad de Panamá', true),
('abogados', 'Bogotá', true),
('lavanderías', 'Mérida', true),
('consultorías empresariales', 'Madrid', true),
('agencias de viajes', 'Buenos Aires', true),
('academias de baile', 'Ciudad de Panamá', true),
('nutriólogos', 'Santiago de Chile', true),
('estudios de tatuaje', 'Puebla', true),
('despachos de arquitectura', 'Guadalajara', true),
('spas', 'León', true),
('academias de idiomas', 'Bilbao', true),
('farmacias', 'Madrid', true),
('cafeterías', 'Ciudad de Panamá', true),
('distribuidoras', 'Guadalajara', true),
('psicólogos', 'Los Ángeles', true),
('coaches de negocios', 'Monterrey', true),
('cafeterías', 'Caracas', true),
('floristerías', 'Tijuana', true),
('empresas de logística', 'Quito', true),
('talleres mecánicos', 'Bogotá', true),
('ópticas', 'Madrid', true),
('centros de coworking', 'León', true),
('cafeterías', 'Montevideo', true),
('clínicas de estética', 'Guadalajara', true),
('restaurantes', 'Bilbao', true),
('constructoras', 'Ciudad de México', true),
('agencias de eventos', 'Los Ángeles', true),
('ópticas', 'Caracas', true),
('agencias de eventos', 'Cali', true),
('constructoras', 'Houston', true),
('agencias de eventos', 'Tijuana', true),
('restaurantes', 'Puebla', true),
('barberías', 'Miami', true),
('lavanderías', 'Santiago de Chile', true),
('consultorías empresariales', 'Bilbao', true),
('estudios de tatuaje', 'Lima', true),
('fábricas', 'Guadalajara', true),
('imprentas', 'Sevilla', true),
('contadores', 'León', true),
('academias de baile', 'Tijuana', true),
('infoproductores', 'Chicago', true),
('infoproductores', 'Monterrey', true),
('escuelas privadas', 'Quito', true),
('spas', 'Tijuana', true),
('guarderías', 'Valencia', true),
('nutriólogos', 'Ciudad de Panamá', true),
('contadores', 'Guadalajara', true),
('coaches de negocios', 'Houston', true),
('constructoras', 'Lima', true),
('nutriólogos', 'Buenos Aires', true),
('academias de baile', 'Puebla', true),
('tiendas de ropa', 'Mérida', true),
('guarderías', 'Nueva York', true),
('ópticas', 'Cali', true),
('talleres mecánicos', 'Ciudad de Panamá', true),
('restaurantes', 'Madrid', true),
('talleres mecánicos', 'Nueva York', true),
('spas', 'Bogotá', true),
('estudios de tatuaje', 'Houston', true),
('inmobiliarias', 'Bogotá', true),
('consultorías empresariales', 'Mérida', true),
('barberías', 'León', true),
('escuelas privadas', 'Querétaro', true),
('guarderías', 'León', true),
('spas', 'Chicago', true),
('nutriólogos', 'Caracas', true),
('clínicas de estética', 'Buenos Aires', true),
('spas', 'Madrid', true),
('academias de baile', 'Nueva York', true),
('joyerías', 'Valencia', true),
('farmacias', 'Nueva York', true),
('infoproductores', 'Miami', true),
('consultorías empresariales', 'Nueva York', true),
('farmacias', 'Ciudad de México', true),
('escuelas privadas', 'Santiago de Chile', true),
('imprentas', 'Nueva York', true),
('tiendas de ropa', 'Ciudad de México', true),
('academias de baile', 'Madrid', true),
('estudios de fotografía', 'Sevilla', true),
('consultorías empresariales', 'Bogotá', true),
('despachos de arquitectura', 'Valencia', true),
('imprentas', 'Ciudad de Panamá', true),
('hoteles', 'Valencia', true),
('abogados', 'Valencia', true),
('constructoras', 'Miami', true),
('agencias de marketing', 'Guadalajara', true),
('talleres mecánicos', 'Medellín', true),
('hoteles', 'Barcelona', true),
('guarderías', 'Cali', true),
('barberías', 'Quito', true),
('infoproductores', 'Quito', true),
('clínicas dentales', 'Cali', true),
('agencias de viajes', 'Querétaro', true),
('tiendas de ropa', 'Querétaro', true),
('joyerías', 'Sevilla', true),
('coaches de negocios', 'Nueva York', true),
('clínicas de estética', 'León', true),
('gimnasios', 'Caracas', true),
('cafeterías', 'Monterrey', true),
('abogados', 'Cali', true),
('spas', 'Barcelona', true),
('psicólogos', 'Bogotá', true),
('escuelas privadas', 'Barcelona', true),
('distribuidoras', 'Puebla', true),
('agencias de eventos', 'Medellín', true),
('ópticas', 'Buenos Aires', true),
('abogados', 'Madrid', true),
('lavanderías', 'Bogotá', true),
('floristerías', 'Sevilla', true),
('despachos de arquitectura', 'Santiago de Chile', true),
('consultorías empresariales', 'Buenos Aires', true),
('tiendas de ropa', 'Valencia', true),
('floristerías', 'Montevideo', true),
('agencias de viajes', 'Puebla', true),
('tiendas de ropa', 'Tijuana', true),
('farmacias', 'Quito', true),
('centros de coworking', 'Tijuana', true),
('veterinarias', 'Bilbao', true),
('estudios de tatuaje', 'Guadalajara', true),
('restaurantes', 'León', true),
('consultorías empresariales', 'Santiago de Chile', true),
('gimnasios', 'Cali', true),
('clínicas de estética', 'Bogotá', true),
('estudios de fotografía', 'Santiago de Chile', true),
('tiendas de ropa', 'Houston', true),
('estudios de tatuaje', 'Bogotá', true),
('constructoras', 'Valencia', true),
('cafeterías', 'Madrid', true),
('agencias de viajes', 'Sevilla', true),
('coaches de negocios', 'Bogotá', true),
('escuelas privadas', 'Bogotá', true),
('infoproductores', 'Querétaro', true),
('lavanderías', 'Bilbao', true),
('hoteles', 'Montevideo', true),
('hoteles', 'Querétaro', true),
('clínicas de estética', 'Tijuana', true),
('empresas de logística', 'Querétaro', true),
('constructoras', 'Bogotá', true),
('estudios de fotografía', 'Medellín', true),
('joyerías', 'Bilbao', true),
('estudios de fotografía', 'Bilbao', true),
('fábricas', 'Medellín', true),
('coaches de negocios', 'Ciudad de Panamá', true),
('agencias de viajes', 'Barcelona', true),
('despachos de arquitectura', 'Lima', true),
('escuelas privadas', 'Monterrey', true),
('talleres mecánicos', 'Guadalajara', true),
('academias de idiomas', 'Puebla', true),
('nutriólogos', 'Montevideo', true),
('spas', 'Quito', true),
('agencias de marketing', 'Tijuana', true),
('clínicas dentales', 'Nueva York', true),
('barberías', 'Caracas', true),
('clínicas de estética', 'Querétaro', true),
('coaches de negocios', 'Valencia', true),
('estudios de tatuaje', 'Mérida', true),
('clínicas dentales', 'Los Ángeles', true),
('restaurantes', 'Buenos Aires', true),
('agencias de eventos', 'Santiago de Chile', true),
('gimnasios', 'Puebla', true),
('despachos de arquitectura', 'Cali', true),
('distribuidoras', 'Lima', true),
('cafeterías', 'Cali', true),
('constructoras', 'Caracas', true),
('agencias de marketing', 'Bilbao', true),
('distribuidoras', 'Ciudad de Panamá', true),
('imprentas', 'Santiago de Chile', true),
('veterinarias', 'Querétaro', true),
('inmobiliarias', 'Montevideo', true),
('imprentas', 'Houston', true),
('agencias de viajes', 'Ciudad de México', true),
('cafeterías', 'Buenos Aires', true),
('nutriólogos', 'Houston', true),
('distribuidoras', 'Valencia', true),
('abogados', 'Montevideo', true),
('nutriólogos', 'León', true),
('guarderías', 'Caracas', true),
('hoteles', 'Chicago', true),
('centros de coworking', 'Barcelona', true),
('centros de coworking', 'Los Ángeles', true),
('nutriólogos', 'Sevilla', true),
('psicólogos', 'Querétaro', true),
('lavanderías', 'Chicago', true),
('psicólogos', 'Nueva York', true),
('floristerías', 'Querétaro', true),
('fábricas', 'Chicago', true),
('tiendas de ropa', 'Puebla', true),
('hoteles', 'Bilbao', true),
('veterinarias', 'Buenos Aires', true),
('cafeterías', 'Medellín', true),
('distribuidoras', 'Bilbao', true),
('agencias de viajes', 'Bilbao', true),
('gimnasios', 'Sevilla', true),
('agencias de eventos', 'Houston', true),
('floristerías', 'Cali', true),
('academias de baile', 'Quito', true),
('abogados', 'Santiago de Chile', true),
('imprentas', 'Montevideo', true),
('agencias de eventos', 'Lima', true),
('fábricas', 'Houston', true),
('consultorías empresariales', 'Ciudad de México', true),
('estudios de fotografía', 'Caracas', true),
('restaurantes', 'Ciudad de Panamá', true),
('empresas de logística', 'Sevilla', true),
('coaches de negocios', 'Barcelona', true),
('fábricas', 'Ciudad de Panamá', true),
('academias de idiomas', 'Nueva York', true),
('centros de coworking', 'Caracas', true),
('joyerías', 'Monterrey', true),
('despachos de arquitectura', 'Querétaro', true),
('coaches de negocios', 'Cali', true),
('agencias de marketing', 'Buenos Aires', true),
('farmacias', 'Barcelona', true),
('imprentas', 'Monterrey', true),
('fábricas', 'Puebla', true),
('clínicas de estética', 'Ciudad de México', true),
('estudios de tatuaje', 'Bilbao', true),
('constructoras', 'Madrid', true),
('inmobiliarias', 'Santiago de Chile', true),
('lavanderías', 'Caracas', true),
('distribuidoras', 'Santiago de Chile', true),
('restaurantes', 'Mérida', true),
('imprentas', 'Quito', true),
('talleres mecánicos', 'Ciudad de México', true),
('joyerías', 'Buenos Aires', true),
('estudios de fotografía', 'León', true),
('ópticas', 'Puebla', true),
('abogados', 'Querétaro', true),
('inmobiliarias', 'Bilbao', true),
('agencias de marketing', 'Puebla', true),
('despachos de arquitectura', 'Bogotá', true),
('joyerías', 'Mérida', true),
('agencias de eventos', 'Buenos Aires', true),
('talleres mecánicos', 'León', true),
('inmobiliarias', 'Guadalajara', true),
('fábricas', 'Nueva York', true),
('abogados', 'Puebla', true),
('estudios de tatuaje', 'Medellín', true),
('empresas de logística', 'Medellín', true),
('hoteles', 'Caracas', true),
('empresas de logística', 'Madrid', true),
('veterinarias', 'Nueva York', true),
('spas', 'Sevilla', true),
('gimnasios', 'Medellín', true),
('gimnasios', 'Lima', true),
('constructoras', 'Cali', true),
('talleres mecánicos', 'Sevilla', true),
('clínicas dentales', 'Madrid', true),
('agencias de marketing', 'Barcelona', true),
('veterinarias', 'León', true),
('constructoras', 'Monterrey', true),
('clínicas dentales', 'Lima', true),
('centros de coworking', 'Madrid', true),
('academias de baile', 'Guadalajara', true),
('academias de idiomas', 'Medellín', true),
('clínicas de estética', 'Lima', true),
('estudios de tatuaje', 'Tijuana', true),
('clínicas dentales', 'Monterrey', true),
('agencias de marketing', 'Lima', true),
('lavanderías', 'Quito', true),
('consultorías empresariales', 'Montevideo', true),
('infoproductores', 'Bilbao', true),
('constructoras', 'Santiago de Chile', true),
('clínicas dentales', 'Ciudad de Panamá', true),
('veterinarias', 'Barcelona', true),
('spas', 'Mérida', true),
('floristerías', 'Bogotá', true),
('joyerías', 'Ciudad de Panamá', true),
('contadores', 'Sevilla', true),
('restaurantes', 'Miami', true),
('farmacias', 'Santiago de Chile', true),
('distribuidoras', 'Mérida', true),
('estudios de fotografía', 'Lima', true),
('contadores', 'Monterrey', true),
('infoproductores', 'Mérida', true),
('psicólogos', 'Chicago', true),
('imprentas', 'León', true),
('agencias de eventos', 'Ciudad de México', true),
('empresas de logística', 'Chicago', true),
('guarderías', 'Querétaro', true),
('agencias de marketing', 'Houston', true),
('empresas de logística', 'Cali', true),
('abogados', 'Barcelona', true),
('guarderías', 'Guadalajara', true),
('academias de idiomas', 'Querétaro', true),
('tiendas de ropa', 'Bogotá', true),
('inmobiliarias', 'Valencia', true),
('clínicas dentales', 'Buenos Aires', true),
('gimnasios', 'León', true),
('consultorías empresariales', 'Miami', true),
('centros de coworking', 'Nueva York', true),
('centros de coworking', 'Guadalajara', true),
('barberías', 'Valencia', true),
('academias de baile', 'Bogotá', true),
('abogados', 'Tijuana', true),
('academias de idiomas', 'Tijuana', true),
('joyerías', 'Santiago de Chile', true),
('barberías', 'Barcelona', true),
('farmacias', 'Buenos Aires', true),
('clínicas de estética', 'Madrid', true),
('inmobiliarias', 'Nueva York', true),
('guarderías', 'Bogotá', true),
('infoproductores', 'Lima', true),
('academias de baile', 'Houston', true),
('inmobiliarias', 'Tijuana', true),
('barberías', 'Bogotá', true),
('coaches de negocios', 'Bilbao', true),
('escuelas privadas', 'Chicago', true),
('imprentas', 'Tijuana', true);
